### ISSUE TITLE
Missing ticket for Google searching request and parsing request result

### ISSUE THREAD

**Issue by junan** [mcneto/ruby-google-search-ic#28]
I am missing ticket for Google searching request and parsing request result. I found this [ticket](https://github.com/mcneto/ruby_google_search_ic/issues/19) which is only for creating model and store search result data.

But to get the data we need to request with each keyword to the Google, get the response, then parse the response to filter necessary data(total result count, total ad link etc). So I think we need ticket/tickets for it

**Comment by mcneto** [comment]
I’ll change [this ticket](#24) to handle request for Google Search for now. And if I want to use API I will open a new ticket again in the future. 🙂
