### ISSUE TITLE
Missing ticket for to view the search result information for each keyword

### ISSUE THREAD

**Issue by junan** [mcneto/ruby-google-search-ic#29]
I am missing ticket for viewing view the search result information for each keyword
![Screen Shot 2021-06-10 at 7 22 16 PM](https://user-images.githubusercontent.com/6076762/121524136-306b4500-ca21-11eb-8518-0194f19dbfb2.png)

**Comment by mcneto** [comment]
Add new tickets (#30, #31, #32) according to this issue.
